### ISSUE TITLE
Unknown server error

### ISSUE THREAD

**Issue by wupasscat** [wupasscat/continent-bot#20]
```
03/08/2023 09:58:22 - discord.client - ERROR - Ignoring exception in on_ready (client.py:515)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/app/bot.py", line 138, in on_ready
    await main() # Run census_client.py
    ^^^^^^^^^^^^
  File "/app/census_client.py", line 249, in main
    open_continents = await _get_open_zones(client, server_id) # Get open continents of server_id
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/census_client.py", line 186, in _get_open_zones
    map_data = await world.map(*_WARPGATE_IDS.keys())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/auraxium/ps2/_world.py", line 107, in map
    payload = await self._client.request(query)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/auraxium/_rest.py", line 157, in request
    data = await run_query(query, verb=verb, session=self.session,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/auraxium/_rest.py", line 507, in run_query
    raise_for_dict(data, url)
  File "/usr/local/lib/python3.11/site-packages/auraxium/_rest.py", line 362, in raise_for_dict
    raise ServerError('Unknown server error', url)
auraxium.errors.ServerError: Unknown server error
```
not sure how to handle this yet

**Comment by wupasscat** [comment]
https://github.com/leonhard-s/auraxium/blob/8fd4fa9eaa77ecd3b4cba571c285a4776aeaa119/auraxium/_rest.py#L357-L365

**Comment by wupasscat** [comment]
According to MangoBean who is the API developer at RPG, the "map" collection "can be picky" so I added a 6 second sleep between queries.

**Comment by wupasscat** [comment]
I've had it running for about 2 hours so far with no issues so I'll close this for now.

**Comment by wupasscat** [comment]
IT HAPPENED AGAIN!

**Comment by wupasscat** [comment]
This solution sucks.  
It should be something like this:
```python
                try:
                    open_continents = await _get_open_zones(client, server_id) # Get open continents of server_id
                except auraxium.errors.ServerError as ServerError:
                    log.error(ServerError)
                    await asyncio.sleep(5)
                    open_continents = await _get_open_zones(client, server_id)
```
